### PR TITLE
Store custom attributes in a map

### LINKED ISSUE #9: AddCustomAttributes does not work when using some middlewares
I've got a handler that is adding some custom attributes to be logged with `slogchi.AddCustomAttributes()`. This works as expected for most routes however if I use a middleware that adds something to the request context the custom attributes are no longer showing on the log. An example middleware that breaks it:

```go
type contextKey string

const ExampleContextKey contextKey = "someKey"

func ExampleMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := context.WithValue(r.Context(), ClientContextKey, "example")
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
```

If I modify the middleware to update the request in place the custom attributes are logged.

```go
type contextKey string

const ExampleContextKey contextKey = "someKey"

func ExampleMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		*r = *r.WithContext(context.WithValue(r.Context(), ClientContextKey, "example"))
		next.ServeHTTP(w, r)
	})
}
```

Is there a way to get custom attributes to work with the first approach? Some chi middlewares like `middleware.Timeout()` use `r.WithContext(ctx)` and it would be great if they were compatible. Thanks for this project!

### PR DESCRIPTION
**Pull request by Serjlee**
Closes #9 

Hey there, since I encountered https://github.com/samber/slog-chi/issues/9 myself, I thought of this possible solution to avoid woes around  the use of `*r = r.WithContext(ctx)`

The idea is to create a `sync.Map` (a regular map would probably suffice, but a `sync.Map` can also work with calls made in  random goroutines spawned from the handler), populate it with `AddCustomAttributes`, then read it after the request ends.

Since the map is accessed via a pointer, I took the chance to also add a `AddContextAttributes` method not requiring the full-blown `*http.Request` (very useful when using Chi with [Huma](https://huma.rocks/))

With this setup, adding custom attributes can easily be done from both handlers and any middlewares mounted after `slog-chi` and other middlewares using `*r = r.WithContext(ctx)` won't interfere anymore.

Let me know if this approach sounds good, I will gladly open a PR for https://github.com/samber/slog-http, too

### CODE REVIEW

**Comment by Serjlee** [comment]
Hey @samber, can I ask you some feedback on this?

File: middleware.go [hunk 1]
```diff
@@ -252,17 +259,16 @@ func NewWithConfig(logger *slog.Logger, config Config) func(http.Handler) http.H
...
+}
 
-	switch attrs := v.(type) {
-	case []slog.Attr:
-		*r = *r.WithContext(context.WithValue(r.Context(), customAttributesCtxKey, append(attrs, attr)))
+// AddContextAttributes is the same as AddCustomAttributes, but it doesn't need access to the request struct.
+func AddContextAttributes(ctx context.Context, attr slog.Attr) {
+	if v := ctx.Value(customAttributesCtxKey); v != nil {
+		m := v.(*sync.Map)
+		m.Store(attr.Key, attr.Value)
```
Comment (samber) [inline middleware.go:271]:
```suggestion
		if m, ok := v.(*sync.Map); ok {
			m.Store(attr.Key, attr.Value)
		}
```

File: middleware.go [hunk 2]
```diff
@@ -231,10 +237,11 @@ func NewWithConfig(logger *slog.Logger, config Config) func(http.Handler) http.H
...
 				if v := r.Context().Value(customAttributesCtxKey); v != nil {
-					switch attrs := v.(type) {
-					case []slog.Attr:
-						attributes = append(attributes, attrs...)
-					}
+					m := v.(*sync.Map)
+					m.Range(func(key, value any) bool {
+						attributes = append(attributes, slog.Attr{Key: key.(string), Value: value.(slog.Value)})
+						return true
+					})
```
Comment (samber) [inline middleware.go:244]:
```suggestion
					if m, ok := v.(*sync.Map); ok {
						m.Range(func(key, value any) bool {
							attributes = append(attributes, slog.Attr{Key: key.(string), Value: value.(slog.Value)})
							return true
						})
					}
```

**Comment by samber** [comment]
Hey @Serjlee 

Thanks for your work on this.

I agree, your proposal looks good.
